login: &login
  adapter: mysql2
  encoding: utf8
  username: root
  password: 'setup#123'
  socket: /tmp/mysql.sock

development:
  database: ppyn_development
  host: 127.0.0.1
  <<: *login

test:
  database: ppyn_test
  host: 127.0.0.1
  <<: *login

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>


