defaults: &defaults 
  pixi:
    alias_length: 12
    key_length: 16
    site_init_free: 100
    max_pixi_amt: 100000.00
    base_price: 5.00
    premium_price: 20.00
    fee: 0.30
    percent: 2.9
    launch_promo_cd: "2013LAUNCH"
    days: 7
    max_pixi_pix: 16
    max_inv_qty: 100
    pixi_post: 'Hi, I found your pixi post and would like to set up a time to discuss it. Please respond and provide me more information. Thank
    you.'
    payment_api: 'balanced'
    credit_card_api: 'balanced'

development:    
  <<: *defaults
  
production:    
  <<: *defaults
  
test:    
  <<: *defaults
