defaults: &defaults 
  pixi:
    alias_length: 12
    key_length: 16
    site_init_free: 100

development:    
  <<: *defaults
  
production:    
  <<: *defaults
  
test:    
  <<: *defaults
