defaults: &defaults
  searchd_binary_name: searchd
  indexer_binary_name: indexer 
  enable_star: true
  min_infix_len: 3

development:
  mysql41: 9306
  bin_path: "C:/Sphinx/bin"
  <<: *defaults

test:
  mysql41: 9307
  bin_path: "C:/Sphinx/bin"
  <<: *defaults

staging:
  mysql41: 9308
  <<: *defaults

production:
  mysql41: 9312
  <<: *defaults
