defaults: &defaults
  bin_path: "C:/Sphinx/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer 
  enable_star: true
  min_infix_len: 3

development:
  mysql41: 9306
  <<: *defaults

test:
  mysql41: 9307
  <<: *defaults
