---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: pixiboard.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-12fc704e
  image_type: t1.micro
  image_id: ami-a43909e1
  security_groups:
  - default
  - web
  external_host: ec2-54-193-55-216.us-west-1.compute.amazonaws.com
  external_ip: 54.193.55.216
  internal_host: ip-172-31-21-120.us-west-1.compute.internal
  internal_ip: 172.31.21.120
  zone: us-west-1b
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: pixiboard.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-5ffc7003
  image_type: t1.micro
  image_id: ami-a43909e1
  security_groups:
  - default
  external_host: ec2-54-193-109-109.us-west-1.compute.amazonaws.com
  external_ip: 54.193.109.109
  internal_host: ip-172-31-16-249.us-west-1.compute.internal
  internal_ip: 172.31.16.249
  zone: us-west-1b
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db02
  domain: pixiboard.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-f5e29caa
  image_type: m1.medium
  image_id: ami-a43909e1
  security_groups:
  - default
  external_host: ec2-54-193-115-114.us-west-1.compute.amazonaws.com
  external_ip: 54.193.115.114
  internal_host: ip-172-31-3-10.us-west-1.compute.internal
  internal_ip: 172.31.3.10
  zone: us-west-1a
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
