defaults: &defaults
  morphology: stem_en
  searchd_binary_name: searchd
  indexer_binary_name: indexer 
  enable_star: true
  min_infix_len: 3

development:
  mysql41: 9306
  bin_path: "C:/Sphinx/bin"
  <<: *defaults

test:
  mysql41: 9307
  bin_path: "C:/Sphinx/bin"
  <<: *defaults

staging:
  mysql41: 9308
  <<: *defaults

production:
  mysql41: 9312
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
  mem_limit: 128M
  pid_file: "/mnt/pixiboard-production/shared/tmp/searchd.pid"
  indices_location: "/mnt/pixiboard-production/shared/db/sphinx"
  configuration_file: "/mnt/pixiboard-production/shared/production.sphinx.conf"
  binlog_path: "/mnt/pixiboard-production/shared/binlog"
  searchd_log: "/mnt/pixiboard-production/shared/log/production.searchd.log"
  query_log: "/mnt/pixiboard-production/shared/log/production.query.log"
